env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  function-paren-newline: 0,
  no-console: 0,
  no-unused-expressions: 0,
  no-use-before-define: 0,
  implicit-arrow-linebreak: 0,
  import/extensions: 0,
  object-curly-newline: 0,
  operator-linebreak: [2, "after"]
}
