name: Test coverage with Codeclimate

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install package
        env:
          DEFAULT_BRANCH: main
        run: make install
      - name: Setup Code Climate test-reporter
          run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - name: Check test coverage
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          run: |
            ./cc-test-reporter before-build
            make test-coverage
            ./cc-test-reporter after-build --exit-code $?
