name: Test with Jest

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install package
        env:
          DEFAULT_BRANCH: main
        run: make install
      - name: Run tests
        env:
          DEFAULT_BRANCH: main
        run: make test
